// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TpDojo.Data;

#nullable disable

namespace TpDojo.Migrations
{
    [DbContext(typeof(TpDojoContext))]
    [Migration("20221220153309_art martiaux 1")]
    partial class artmartiaux1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BO.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Degat")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arme");
                });

            modelBuilder.Entity("BO.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArtMartial");
                });

            modelBuilder.Entity("BO.Samurai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId")
                        .IsUnique()
                        .HasFilter("[ArmeId] IS NOT NULL");

                    b.ToTable("Samurai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Force = 1326,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 2,
                            Force = 1424,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 3,
                            Force = 185,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 254,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 5,
                            Force = 437,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 6,
                            Force = 1196,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 7,
                            Force = 823,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 8,
                            Force = 888,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 9,
                            Force = 1955,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 10,
                            Force = 931,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 11,
                            Force = 1431,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 565,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 13,
                            Force = 1017,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 14,
                            Force = 1177,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 15,
                            Force = 535,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 16,
                            Force = 875,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 17,
                            Force = 1616,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 18,
                            Force = 1966,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 19,
                            Force = 1958,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 20,
                            Force = 1437,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 21,
                            Force = 1272,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 22,
                            Force = 152,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 23,
                            Force = 704,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 24,
                            Force = 1235,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 25,
                            Force = 1969,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 26,
                            Force = 1622,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 1223,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 1746,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 635,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 30,
                            Force = 532,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 31,
                            Force = 1142,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 32,
                            Force = 1952,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 33,
                            Force = 1969,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 1933,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 1574,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 272,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 37,
                            Force = 1568,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 38,
                            Force = 729,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 39,
                            Force = 1227,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 40,
                            Force = 1740,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 41,
                            Force = 1607,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 42,
                            Force = 878,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 43,
                            Force = 1204,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 44,
                            Force = 1050,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 45,
                            Force = 1064,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 46,
                            Force = 170,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 47,
                            Force = 311,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 48,
                            Force = 1906,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 49,
                            Force = 120,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 50,
                            Force = 1108,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 51,
                            Force = 198,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 52,
                            Force = 690,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 53,
                            Force = 1843,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 54,
                            Force = 653,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 55,
                            Force = 173,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 56,
                            Force = 1598,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 57,
                            Force = 221,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 58,
                            Force = 1204,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 59,
                            Force = 834,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 60,
                            Force = 1017,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 61,
                            Force = 837,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 62,
                            Force = 1696,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 63,
                            Force = 1739,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 64,
                            Force = 1801,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 65,
                            Force = 264,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 66,
                            Force = 1666,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 67,
                            Force = 220,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 68,
                            Force = 906,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 140,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 70,
                            Force = 1730,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 71,
                            Force = 1638,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 72,
                            Force = 788,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 73,
                            Force = 166,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 74,
                            Force = 729,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 75,
                            Force = 496,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 76,
                            Force = 1042,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 77,
                            Force = 340,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 78,
                            Force = 1926,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 79,
                            Force = 48,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 80,
                            Force = 843,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 81,
                            Force = 891,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 82,
                            Force = 957,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 83,
                            Force = 1915,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 84,
                            Force = 42,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 85,
                            Force = 1559,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 576,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 87,
                            Force = 1801,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 88,
                            Force = 645,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 89,
                            Force = 583,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 90,
                            Force = 1606,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 91,
                            Force = 1145,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 92,
                            Force = 1761,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 93,
                            Force = 1764,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 94,
                            Force = 1616,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 95,
                            Force = 1518,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 1546,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 97,
                            Force = 147,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 98,
                            Force = 879,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 99,
                            Force = 1931,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 100,
                            Force = 322,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 101,
                            Force = 726,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 102,
                            Force = 426,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 103,
                            Force = 604,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 104,
                            Force = 66,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 105,
                            Force = 286,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 206,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1173,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 108,
                            Force = 566,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1979,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 110,
                            Force = 653,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 111,
                            Force = 788,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 112,
                            Force = 338,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 113,
                            Force = 1146,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 114,
                            Force = 631,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 115,
                            Force = 1201,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 116,
                            Force = 1329,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 117,
                            Force = 1758,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 118,
                            Force = 1732,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 119,
                            Force = 349,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 120,
                            Force = 530,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 121,
                            Force = 1349,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 122,
                            Force = 707,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 123,
                            Force = 1689,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 124,
                            Force = 188,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 125,
                            Force = 1745,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 126,
                            Force = 1193,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 127,
                            Force = 77,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 128,
                            Force = 273,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 129,
                            Force = 510,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 130,
                            Force = 1118,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 131,
                            Force = 1466,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 132,
                            Force = 1250,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 133,
                            Force = 607,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 134,
                            Force = 851,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 135,
                            Force = 301,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 136,
                            Force = 1435,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 137,
                            Force = 1754,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 138,
                            Force = 1810,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 139,
                            Force = 526,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 140,
                            Force = 760,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 141,
                            Force = 840,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 142,
                            Force = 397,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 143,
                            Force = 1430,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1844,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 145,
                            Force = 1922,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 146,
                            Force = 1680,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 147,
                            Force = 1938,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 148,
                            Force = 1421,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 149,
                            Force = 1845,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 150,
                            Force = 1777,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 151,
                            Force = 1718,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 152,
                            Force = 1610,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 153,
                            Force = 1173,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 154,
                            Force = 1317,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 155,
                            Force = 719,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 156,
                            Force = 1320,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 157,
                            Force = 9,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1135,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 159,
                            Force = 1089,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 160,
                            Force = 172,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 323,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 162,
                            Force = 562,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 163,
                            Force = 1168,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 164,
                            Force = 577,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 165,
                            Force = 176,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 166,
                            Force = 95,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 167,
                            Force = 455,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 168,
                            Force = 1384,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 169,
                            Force = 910,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 170,
                            Force = 552,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 171,
                            Force = 1265,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 172,
                            Force = 299,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 173,
                            Force = 1547,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 174,
                            Force = 1343,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 175,
                            Force = 599,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 176,
                            Force = 1155,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 177,
                            Force = 1609,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 178,
                            Force = 198,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 759,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 180,
                            Force = 46,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 181,
                            Force = 101,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 182,
                            Force = 456,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 183,
                            Force = 440,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 184,
                            Force = 697,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 185,
                            Force = 474,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 186,
                            Force = 1307,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 187,
                            Force = 443,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 188,
                            Force = 750,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 189,
                            Force = 1859,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 190,
                            Force = 692,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1272,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 192,
                            Force = 1265,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 240,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 194,
                            Force = 1298,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 195,
                            Force = 207,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 196,
                            Force = 170,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 197,
                            Force = 738,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 198,
                            Force = 1477,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 1607,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 200,
                            Force = 14,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 201,
                            Force = 504,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 202,
                            Force = 1503,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 203,
                            Force = 485,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 204,
                            Force = 1332,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 205,
                            Force = 1794,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 1651,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 207,
                            Force = 1598,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 208,
                            Force = 1149,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 209,
                            Force = 783,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 210,
                            Force = 837,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 211,
                            Force = 1119,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 212,
                            Force = 1962,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 213,
                            Force = 1816,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 214,
                            Force = 350,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 215,
                            Force = 760,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 216,
                            Force = 1703,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 217,
                            Force = 380,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 218,
                            Force = 166,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 219,
                            Force = 161,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 1466,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 221,
                            Force = 1539,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 222,
                            Force = 737,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 223,
                            Force = 1920,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 224,
                            Force = 1553,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 225,
                            Force = 780,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 226,
                            Force = 363,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 227,
                            Force = 652,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 228,
                            Force = 184,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 229,
                            Force = 1722,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1747,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 371,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 232,
                            Force = 589,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 233,
                            Force = 848,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1519,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 235,
                            Force = 150,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 236,
                            Force = 647,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 237,
                            Force = 103,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 1109,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 239,
                            Force = 585,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 1375,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 241,
                            Force = 1938,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 242,
                            Force = 1351,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 243,
                            Force = 1520,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 244,
                            Force = 321,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 245,
                            Force = 318,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 246,
                            Force = 708,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 247,
                            Force = 640,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 248,
                            Force = 826,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 249,
                            Force = 859,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 1300,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 251,
                            Force = 801,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 252,
                            Force = 68,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 253,
                            Force = 2,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 1884,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 255,
                            Force = 1484,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 256,
                            Force = 1781,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 257,
                            Force = 1206,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 1713,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 259,
                            Force = 1364,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1357,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 1111,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 262,
                            Force = 202,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 263,
                            Force = 1919,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 264,
                            Force = 852,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 265,
                            Force = 1973,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 266,
                            Force = 1642,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 267,
                            Force = 1017,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 268,
                            Force = 361,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 269,
                            Force = 1159,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 270,
                            Force = 1385,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 271,
                            Force = 1655,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 272,
                            Force = 844,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 1474,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1787,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 275,
                            Force = 1820,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 276,
                            Force = 1715,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 277,
                            Force = 566,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 278,
                            Force = 552,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 279,
                            Force = 115,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 280,
                            Force = 1648,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1512,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 282,
                            Force = 929,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 283,
                            Force = 1799,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1298,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 285,
                            Force = 498,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 286,
                            Force = 8,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 287,
                            Force = 1894,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 288,
                            Force = 1844,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 289,
                            Force = 235,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 290,
                            Force = 691,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 291,
                            Force = 1544,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 292,
                            Force = 380,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 293,
                            Force = 1624,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 294,
                            Force = 732,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 295,
                            Force = 169,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 527,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 1369,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 426,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 1299,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 1026,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 301,
                            Force = 308,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 302,
                            Force = 605,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 303,
                            Force = 546,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 304,
                            Force = 855,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 305,
                            Force = 1022,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 306,
                            Force = 1942,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 307,
                            Force = 581,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 308,
                            Force = 1392,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 309,
                            Force = 261,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 310,
                            Force = 465,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 311,
                            Force = 604,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 312,
                            Force = 944,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 313,
                            Force = 792,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 38,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 315,
                            Force = 248,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 316,
                            Force = 298,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 317,
                            Force = 981,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 808,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 1508,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 1496,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("SamuraiArt", b =>
                {
                    b.Property<int>("ArtMartiauxId")
                        .HasColumnType("int");

                    b.Property<int>("SamuraisId")
                        .HasColumnType("int");

                    b.HasKey("ArtMartiauxId", "SamuraisId");

                    b.HasIndex("SamuraisId");

                    b.ToTable("SamuraiArt");
                });

            modelBuilder.Entity("BO.Samurai", b =>
                {
                    b.HasOne("BO.Arme", "Arme")
                        .WithOne()
                        .HasForeignKey("BO.Samurai", "ArmeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Arme");
                });

            modelBuilder.Entity("SamuraiArt", b =>
                {
                    b.HasOne("BO.ArtMartial", null)
                        .WithMany()
                        .HasForeignKey("ArtMartiauxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BO.Samurai", null)
                        .WithMany()
                        .HasForeignKey("SamuraisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
